imports:
        - { resource: "@SazhinBlogBundle/Resources/config/events/post_events.yml" }
        - { resource: "@SazhinBlogBundle/Resources/config/events/comment_events.yml" }
        - { resource: "@SazhinBlogBundle/Resources/config/handlers/post_handlers.yml" }
        - { resource: "@SazhinBlogBundle/Resources/config/handlers/comment_handler.yml" }
######################################################################################
services:

    #Менеджер постов
    sazhin.post.post_manager:
              class: Sazhin\BlogBundle\DomainManager\PostManager
              arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']

    #Менеджер комментариев
    sazhin.post.comment_manager:
              class: Sazhin\BlogBundle\DomainManager\CommentManager
              arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']