post_index:
    path:     /
    defaults: { _controller: "SazhinBlogBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{slug}
    defaults: { _controller: "SazhinBlogBundle:Post:show" }
    methods:  [GET, POST]
