<?php

namespace Sazhin\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPublishedPosts()
    {
        return $this->createQueryBuilder('post')
            ->where('post.currentPlace = :state')
            ->setParameter('state', 'published')
            ->getQuery()->getResult();
    }

    public function getPostsByState(string $state)
    {
        return $this->createQueryBuilder('post')
            ->where('post.currentPlace = :state')
            ->setParameter('state', $state)
            ->getQuery()->getResult();
    }

}